name: wallet_apps
description: A new Flutter project. 

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+104

#6 feature
#8 debug
#1 refactor
#last 8 build
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

# parts:
#   uet-lms:
#     source: .
#     plugin: flutter
#     flutter-target: lib/main.dart
#     build-packages:
#       - libsecret-1-dev
#       - libjsoncpp-dev
#     stage-packages:
#       - libsecret-1-dev
#       - libjsoncpp-dev
      
dependencies:
  cupertino_icons:

  flutter:
    sdk: flutter
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  google_fonts: ^3.0.1

  awesome_select: ^6.0.0

  # Icons
  iconsax: ^0.0.8
  unicons: ^2.1.0
  auth_buttons: ^3.0.0

  # silder
  carousel_slider: ^4.1.1 
  smooth_page_indicator: ^1.0.0+2
  flutter_slidable: ^2.0.0

  geolocator: ^9.0.1
  geocoding: ^2.0.5

  gsheets: ^0.4.2
  modal_bottom_sheet: ^2.1.2

  # Storage
  get_storage: ^2.0.3
  shared_preferences: ^2.0.15
  flutter_dotenv: ^5.0.2
  cached_network_image: ^3.2.2

  # Backend
  http: ^0.13.5
  connectivity_plus: ^2.3.6+1
  get: ^4.6.5
  graphql_flutter: ^5.1.0
  async:
  firebase_auth:
  firebase_core:
  google_sign_in: ^5.4.2

  # Image service
  intl: ^0.17.0

  ######## Permission Package ########
  # Camera
  qr_flutter: 
  image_picker:

  # Chart
  fl_chart: ^0.46.0
  pie_chart: ^5.3.2
  coupon_uikit: ^0.0.1+2

  # Icons
  crypto_font_icons: ^1.0.1
  line_awesome_flutter: ^2.0.0
  pinput: ^2.2.12
  date_format: ^2.0.6

  store_redirect: ^2.0.1
  share_plus: ^4.1.0

  vibration: ^1.7.6
 
  # Apps Configuration
  rename: ^2.0.1
  package_info_plus: ^1.4.3+1
  shimmer: ^2.0.0

  # Authentication & Verification
  permission_handler: 10.0.0
  local_auth: ^2.1.2
  web_socket_channel: ^2.2.0
  intl_phone_number_input: ^0.7.1
  flutter_verification_code: ^1.1.6

  animations: ^2.0.4
  animated_background: ^2.0.0
  provider: ^6.0.3
  web3dart:
  bip39: ^1.0.6

  dart_ecpair: ^1.0.2
  defichaindart: ^3.8.7+3

  flutter_secure_storage: ^6.0.0
  # flutter_screenshot_switcher: ^2.1.0

  #Contact
  fluttercontactpicker: ^4.7.0
  
  #animation
  responsive_framework: ^0.2.0
  flutter_launcher_icons: ^0.10.0
  url_launcher: ^6.1.5
  loading_indicator: ^3.1.0
  fluttertoast: ^8.0.9
  in_app_update: ^3.0.0
  tutorial_coach_mark: ^1.2.4
  transition: ^2.0.2
  lottie: ^1.4.2
  motion_toast: ^2.3.2
  flutter_svg: ^1.1.4
  animate_do: ^2.1.0

  # flutter lock passcode
  flutter_screen_lock: ^7.0.4
  ai_progress: ^2.0.0
  responsive_sizer: ^3.1.0
  sizer: ^2.0.15
  action_slider: ^0.6.0

  # Third-party
  walletconnect_dart: ^0.0.11
  wallet_connect: ^1.0.2
  eth_sig_util: ^0.0.9
  flutter_stripe: ^7.0.0

  # Device Preview
  device_preview:

  flutter_native_splash: ^2.2.8
  random_avatar: ^0.0.7

  # Download
  path_provider:

  external_app_launcher: ^3.1.0

  dropdown_button2: ^1.7.2
  showcaseview: ^2.0.0+1
  form_validation: ^2.1.0+22
  syncfusion_flutter_datepicker: ^20.3.60
  flutter_multi_formatter: ^2.9.11
  video_player: ^2.4.9
  liquid_progress_indicator: ^0.4.0
  animated_text_kit: ^4.2.2

dependency_overrides:
    # git:
    #   url: https://github.com/polkawallet-io/ui.git
    #   ref: 485a9cde97f2446d74a1aeb6d8d63e33683461a5

  # polkawallet_sdk: 0.4.8 # // Work For Android But not work for iOS
  polkawallet_sdk: 0.5.0 # // Work For iOS But not work for Android
  permission_handler: ^9.2.0
  qr_code_scanner: ^1.0.0
  
  # webview_flutter
  flutter_inappwebview: ^5.4.3+7

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

# run: flutter clean && flutter pub get && flutter pub run flutter_native_splash:create
flutter_native_splash: 
  color: "#023859"
  
  image: assets/logo/bitriel-splash.png
  android: true
  android12: false
  ios: true
 

# Run command: flutter pub run flutter_launcher_icons:main 
flutter_icons:
  image_path: "assets/logo/bitriel_icon.png"
  ios: true
  android: true


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/
    - assets/github/
    - assets/abi/
    - assets/icons/
    - assets/token_logo/
    - assets/json/
    - assets/logo/
    - assets/ads/
    - assets/ads/mdw/
    - assets/illustration/
    - assets/payment/
    - .env

    # - ../assets/
    # - ../assets/github/
    # - ../assets/abi/
    # - ../assets/icons/
    # - ../assets/token_logo/
    # - ../assets/json/
    # - ../assets/logo/
    # - ../assets/illustration/
    
    # Animation Flare
    - assets/animation/
    - lib/src/js_api/
    - lib/src/js_api/dist/main.js

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
    - family: Avenir
      fonts:
        - asset: assets/fonts/avenir_ff/AvenirLTStd-Roman.otf

    - family: Prompt
      fonts:
        - asset: assets/fonts/prompt/Prompt-Black.ttf
        - asset: assets/fonts/prompt/Prompt-Bold.ttf
        - asset: assets/fonts/prompt/Prompt-Regular.ttf
        - asset: assets/fonts/prompt/Prompt-Light.ttf
        - asset: assets/fonts/prompt/Prompt-Medium.ttf
        - asset: assets/fonts/prompt/Prompt-SemiBold.ttf
        - asset: assets/fonts/prompt/Prompt-Thin.ttf
        - asset: assets/fonts/prompt/Prompt-ExtraBold.ttf
        - asset: assets/fonts/prompt/Prompt-ExtraLight.ttf

    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow/Barlow-Black.ttf
        - asset: assets/fonts/Barlow/Barlow-Bold.ttf
        - asset: assets/fonts/Barlow/Barlow-Regular.ttf
        - asset: assets/fonts/Barlow/Barlow-Light.ttf
        - asset: assets/fonts/Barlow/Barlow-Medium.ttf
        - asset: assets/fonts/Barlow/Barlow-SemiBold.ttf
        - asset: assets/fonts/Barlow/Barlow-Thin.ttf
        - asset: assets/fonts/Barlow/Barlow-ExtraBold.ttf
        - asset: assets/fonts/Barlow/Barlow-ExtraLight.ttf

  uses-material-design: true
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  #module:
   # androidX: true